uploads = []
generated = []

[[outputs]]
id = "DDT96FitxneXt2hDxAi3l"
uri = "file://knapsack-analyzer.tar.gz"
type = "unspecified"
title = "Knapsack Algorithm Analyzer (source)"

[[outputs]]
id = "trc3RrfY4jI-qr4pBXeTo"
uri = "file://knapsack-analyzer-standalone.tar.gz"
type = "unspecified"
title = "Knapsack Analyzer — Standalone with Multi-Language Support"

[[outputs]]
id = "txRUEdGC8Lv7Vx3fsqWT2"
uri = "file://knapsack-algorithm-analyzer.tar.gz"
type = "unspecified"
title = "Knapsack Algorithm Analyzer — Standalone"
